### ISSUE TITLE
ebay.com

### ISSUE THREAD

**Issue by mhabedan** [wanhose/cookie-dialog-monster#863]
🖥️ Browser
Firefox (115.14.0esr)

📝 Reason
Popup showed up

🔗 URL
https://www.ebay.com/

🏷️ Version
7.1.5.1

**Comment by wanhose** [comment]
> 🖥️ Browser Firefox (115.14.0esr)
> 
> 📝 Reason Popup showed up
> 
> 🔗 URL https://www.ebay.com/
> 
> 🏷️ Version 7.1.5.1

Hi @mhabedan,

This issue was fixed in `7.2.2`, so please update your extension manually. I've also added auto-updates from `7.2.1` so you won't need to do this anymore.

Thanks for the report and welcome to the project! 👋

**Comment by NobleTwo** [comment]
Hi @wanhose!

Thanks for the speedy reaction! Unfortunately, even after upgrading to `7.2.2` the issue persists for me (browser and browser version unchanged).

**Comment by wanhose** [comment]
> Hi @wanhose!
> 
> Thanks for the speedy reaction! Unfortunately, even after upgrading to `7.2.2` the issue persists for me (browser and browser version unchanged).

Hi @NobleTwo,

Can you add more information? For me, it's working like a charm 😅 

https://github.com/user-attachments/assets/b48bae95-3dd3-405b-9990-57c17395d0ca

**Comment by NobleTwo** [comment]
Hi!
Unfortunately, for me it doesn't work: 

[recording](https://github.com/user-attachments/assets/2458b65e-1f6c-4f46-96d6-1c69e6bf0bde)

Might well be that this is related to the browser version. I'm using this Firefox version because it's the default (stable) package for debian (https://packages.debian.org/stable/web/firefox-esr). Not sure why they're not switching to a newer version by now.

**Comment by wanhose** [comment]
> Hi! Unfortunately, for me it doesn't work:
> 
>  simplescreenrecorder-2024-09-09_10.28.54.mp4 
> Might well be that this is related to the browser version. I'm using this Firefox version because it's the default (stable) package for debian (https://packages.debian.org/stable/web/firefox-esr). Not sure why they're not switching to a newer version by now.

Hi @NobleTwo,

Can you check if you have this permission enabled?

![image](https://github.com/user-attachments/assets/8b941247-d735-4732-ab24-aa30194b1d81)

I've also had some issues with Linux versions of my browsers if they were installed through flatpak (or directly from the ditro store). Have you tried [this](https://linuxiac.com/how-to-install-the-latest-firefox-on-debian-12/)?

**Comment by NobleTwo** [comment]
Hi!

I think those permissions are all set correctly:
![Screenshot_0](https://github.com/user-attachments/assets/4e38b12c-08da-46bd-8a31-649a60be5217)

![Screenshot_1](https://github.com/user-attachments/assets/1c41ba14-557d-4f7b-ab3b-35b9349cc79e)

Didn't want to manually upgrade Firefox but did it now for science. ;) And you're right indeed, that fixes the issue. Would it make sense to flag somewhere that Firefox >115 is needed for this Cookie Dialog Monster to run properly?

Anyway, thanks for following up on this issue so quickly!

**Comment by wanhose** [comment]
> Hi!
> 
> I think those permissions are all set correctly: ![Screenshot_0](https://private-user-images.githubusercontent.com/22447386/365964148-4e38b12c-08da-46bd-8a31-649a60be5217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTUxMTIsIm5iZiI6MTcyNTk5NDgxMiwicGF0aCI6Ii8yMjQ0NzM4Ni8zNjU5NjQxNDgtNGUzOGIxMmMtMDhkYS00NmJkLThhMzEtNjQ5YTYwYmU1MjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE5MDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1OTc1Y2NjMTI3NzZjYThmYmMwZTQzYTM5ODVjYTc2ZTNlNjdjNTdiZmRiN2M4ZjVkYzMxODRkMDgzYTBlNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z1MTY-KMXaMpk8E6UKcNFBVw5E7-e2jl0FY-x_pvSWA)
> 
> ![Screenshot_1](https://private-user-images.githubusercontent.com/22447386/365964173-1c41ba14-557d-4f7b-ab3b-35b9349cc79e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTUxMTIsIm5iZiI6MTcyNTk5NDgxMiwicGF0aCI6Ii8yMjQ0NzM4Ni8zNjU5NjQxNzMtMWM0MWJhMTQtNTU3ZC00ZjdiLWFiM2ItMzViOTM0OWNjNzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE5MDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYzcyZDJkOTllMzc4MzU2NDA5Y2Y5MzYxMGQyMTA4YzgxNGEwYzA1MjFiMWY4MzRhOWE5MjlkN2UwMjE3ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._7fdzb_27v4TmKP27k9w95OW_wnizGYumRvKbWQs_sE)
> 
> Didn't want to manually upgrade Firefox but did it now for science. ;) And you're right indeed, that fixes the issue. Would it make sense to flag somewhere that Firefox >115 is needed for this Cookie Dialog Monster to run properly?
> 
> Anyway, thanks for following up on this issue so quickly!

Absolutely, will do it. Just need some time to find the minimum version, I'm going to try from `115.x` on.

Thank you again! 🎖️
