### ISSUE TITLE
gla.ac.uk

### ISSUE THREAD

**Issue by NobleTwo** [wanhose/cookie-dialog-monster#864]
🖥️ Browser
Firefox (115.14.0esr)

📝 Reason
Popup showed up

🔗 URL
https://www.gla.ac.uk

🏷️ Version
7.1.5.1

**Comment by wanhose** [comment]
> 🖥️ Browser Firefox (115.14.0esr)
> 
> 📝 Reason Popup showed up
> 
> 🔗 URL https://www.gla.ac.uk
> 
> 🏷️ Version 7.1.5.1

Hi @NobleTwo,

This issue was fixed in `7.2.2`, so please update your extension manually. I've also added auto-updates from `7.2.1` so you won't need to do this anymore.

Thanks for the report and welcome to the project! 👋

**Comment by NobleTwo** [comment]
Hi @wanhose!

Thanks for the speedy reaction! Unfortunately, even after upgrading to 7.2.2 the issue persists for me (browser and browser version unchanged).

**Comment by wanhose** [comment]
Hi @NobleTwo,

Can you add more information? For me, it's working like a charm 😅 

https://github.com/user-attachments/assets/18cb1bba-1448-43c8-84f8-fda1d0247b42

**Comment by NobleTwo** [comment]
As mentioned in #863, quite possible that it's related to the browser version. This is what it looks like for me:

[recording](https://github.com/user-attachments/assets/e5ba9a20-4e75-441c-88b3-f4a3868a90c3)

**Comment by wanhose** [comment]
> As mentioned in #863, quite possible that it's related to the browser version. This is what it looks like for me:
> 
>  simplescreenrecorder-2024-09-09_10.38.00.mp4

Hi @NobleTwo,

Can you check if you have this permission enabled?

![image](https://github.com/user-attachments/assets/8b941247-d735-4732-ab24-aa30194b1d81)

**Comment by NobleTwo** [comment]
Hi!

As mentioned in #863, the permissions are probably set correctly. Switching to a newer Firefox version resolves the issue though.

Thanks!
