### ISSUE TITLE
Google, both desktop and mobile (since a couple of days ago)

### ISSUE THREAD

**Issue by alleluia20** [wanhose/cookie-dialog-monster#921]
Hello,

The extension used to close the Google cookie dialogue a couple of days ago, but it is not closed any more  (at least, the Spanish version). Maybe has the Google cookie dialogue changed?

The cookie dialogue is displayed both on the desktop (using Chrome in my case) and on the mobile phone (using Kiwi browser in my case).

I previously submitted #917 because I thought that the issue only applied to the mobile site. After realising that it applies to both desktop and mobile, I am submitting this new bug and I am closing #917 as a duplicate.

Thank you.

**Comment by wanhose** [comment]
> Hello,
> 
> The extension used to close the Google cookie dialogue a couple of days ago, but it is not closed any more (at least, the Spanish version). Maybe has the Google cookie dialogue changed?
> 
> The cookie dialogue is displayed both on the desktop (using Chrome in my case) and on the mobile phone (using Kiwi browser in my case).
> 
> I previously submitted #917 because I thought that the issue only applied to the mobile site. After realising that it applies to both desktop and mobile, I am submitting this new bug and I am closing #917 as a duplicate.
> 
> Thank you.

Hi @alleluia20,

You are right. This was a regression, database version `>= 1725777170641` should fix it.

Sorry for the inconveniences 🙏

**Comment by alleluia20** [comment]
Hello,

Not fixed yet... The English dialogue is closed, but the Spanish version
(the one that shows to me) is not closed...

I presume that the issue will also apply to other languages, not only
Spanish...

Thank you.

**Comment by wanhose** [comment]
> Hello, Not fixed yet... The English dialogue is closed, but the Spanish version (the one that shows to me) is not closed... I presume that the issue will also apply to other languages, not only Spanish... Thank you.

Hi @alleluia20,

It was working a few days ago, I tested it personally but they seem to have removed an attribute from the dialog that was the one I was using to remove it. So the extension doesn't find the dialog already.

I will need to take a look deeper because at a first look doesn't seem to have an alternate attribute to select by.

Thanks again, will take a look soon 🙏

**Comment by wanhose** [comment]
Hi @alleluia20,

Please, update your database version to `>= 1726393651312`.

Thanks!  💯
